# Generated by Django 5.1.1 on 2024-09-14 23:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_event_data_hora_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='data_hora_fim',
        ),
        migrations.RemoveField(
            model_name='event',
            name='data_hora_inicio',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
